### ISSUE TITLE
AMQP rule does not accept null for channel_filter

### ISSUE THREAD

**Issue by kandreasyan** [ably/terraform-provider-ably#151]
Ably AMQP rule does not accept null for channel_filter(it is a mandatory field) but when I set match everything/leave blank in the UI it stores a null in the state file.

```
resource "ably_rule_amqp" "rule_amqp" {
Must set a configuration value for the source.channel_filter attribute as the provider has marked it as required.
```

I can use a regular expression that matches everything, but I am not sure that will work as expected.

**Comment by Morganamilo** [comment]
It seems the REST API we are calling to manage rules requires this field when it really shouldn't. Asking the web team for a fix and once that lands we can fix it here too.

**Comment by Morganamilo** [comment]
So it seems that the API wants an empty string not a null. So you can just set the value to an empty string as a work around. I have a PR up that makes the field optional so a null will also work on the terraform side.

**Comment by kandreasyan** [comment]
@Morganamilo Thank you!
