### ISSUE TITLE
Expose `exchange` for AMQP rule

### ISSUE THREAD

**Issue by jamienewcomb** [ably/terraform-provider-ably#159]
We have added a new customisable interpolable field to a Rule , where a customer can essentially specify a key for the rabbitMQ exchange they wish to route to (the field is `exchange` , and behaves identically to the `routingKey` behind the scenes in terms of the interpolation available) .

**Comment by graham-russell** [comment]
This is done. It is available in v0.6.1 of the Ably Terraform provider.
