### ISSUE TITLE
Following instructions for importing configuration doesn't work

### ISSUE THREAD

**Issue by kavalerov** [ably/terraform-provider-ably#181]
I have prepared the following main.tf: 

```terraform
terraform {

  required_providers {
    ably = {
      source = "ably/ably"
    }
  }
}

provider "ably" {
  token = "control api token"
}

resource "ably_app" "app0" {
  name   = "prod"
  status = "enabled"
}
```

And then I do the following when try to import configuration (basically copied from the [guide on Terraform website](https://registry.terraform.io/providers/ably/ably/latest/docs#importing-existing-resources):

![image](https://github.com/ably/terraform-provider-ably/assets/1847904/8d1b12c0-4874-431b-9b55-a9131898d6be)

```
❯ terraform import ably_app.app0 prod
ably_app.app0: Importing from ID "prod"...
ably_app.app0: Import prepared!
  Prepared ably_app for import
ably_app.app0: Refreshing state... [id=prod]
╷
│ Error: Cannot import non-existent remote object
│
│ While attempting to import an existing object to "ably_app.app0", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that the id is correct and that it is associated with the provider's
│ configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
```

It looks like  it tries to use name that I provided as appid, which is not correct.

**Comment by kavalerov** [comment]
@graham-russell I was wondering if you had any time to look at this by any chance?

**Comment by graham-russell** [comment]
Hey @kavalerov - I just had a look. You need to import the app using it's app id rather than name. 

I got the account id from the Ably dashboard - https://ably.com/accounts/12345/apps/12345/edit. There are other ways to do that as well.

Running `import ably_app.app0 {APP_ID}` worked for me.

I'm currently using OpenTofu but Terraform will work the same way:


```
> tofu import ably_app.app0 XXXXXX                                                                                                                                                                               09:34:49
ably_app.app0: Importing from ID "XXXXXX"...
ably_app.app0: Import prepared!
  Prepared ably_app for import
ably_app.app0: Refreshing state... [id=XXXXXX]

Import successful!

The resources that were imported are shown above. These resources are now in
your OpenTofu state and will henceforth be managed by OpenTofu.
```
