### ISSUE TITLE
Design authentication flow for the Terraform provider users

### ISSUE THREAD

**Issue by kavalerov** [ably/terraform-provider-ably#3]
We need to make decision on how we want users to provide Control API access token to the provider to be able to access the service. 

For reference, AWS provider supports a variety of ways for this: https://registry.terraform.io/providers/hashicorp/aws/latest/docs#authentication-and-configuration

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/IAC-7) by [Unito](https://www.unito.io)

**Comment by kavalerov** [comment]
Considering we are working on the first version of the provider at the moment, I suggest we keep things simple and support only providing access token via parameter in the provider declaration, i.e. 

```
provider "ably" {
  access_token = var.ably_access_token
}
```

and then user can provide the value for the corresponding input variable using a variety of methods, i.e. via [command line argument](https://www.terraform.io/language/values/variables#variables-on-the-command-line), [tfvars file](https://www.terraform.io/language/values/variables#variable-definitions-tfvars-files) or as [environment variables](https://www.terraform.io/language/values/variables#environment-variables)

**Comment by kavalerov** [comment]
@graham-russell can we say that this was closed by #28 ? It includes authentication, and the code in the repo is the best way to document the behaviour (I guess the only thing missing may be adding docs specifically for token in the provider declaration)

**Comment by graham-russell** [comment]
I agree @kavalerov . If we want to add additional methods in future then let's create new issues/work items.
For now, the user can authenticate via env vars or by specifying url/token in provider HCL config.
