### ISSUE TITLE
Implement the Kinesis rule target resource

### ISSUE THREAD

**Issue by kavalerov** [ably/terraform-provider-ably#39]
Implement 3 resources (as specified in [https://github.com/ably/terraform-provider-ably/blob/main/examples/resources/rule_aws_kinesis.tf](https://github.com/ably/terraform-provider-ably/blob/main/examples/resources/rule_aws_kinesis.tf|smart-link) ):

* `ably_rule`
* `ably_rule_source`
* `ably_rule_target_aws_kinesis`

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/IAC-44) by [Unito](https://www.unito.io)

**Comment by graham-russell** [comment]
Done in #100
