### ISSUE TITLE
Create an "shell" implementation of the provider that will provide full interface but will make no calls to API

### ISSUE THREAD

**Issue by kavalerov** [ably/terraform-provider-ably#4]
As there is work done in parallel on the Go library for Control API, we can still make progress on the provider by building a prototype, which will declare all the inputs and resources that provider exposes, while not actually do any changes in Ably infrastructure. 

Having such implementation early on will enable us to do several things: 

1. it will be something we can showcase to potential users to get their feedback (arguably we can do it even without fake implementation, but this way we can even run `terraform plan` and `terraform apply` to showcase it)
1. It will provide us with something we can start writing our documentation on
1. It will force us to think early about the user experience and imposing all the right validations and restrictions on the user input early on

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/IAC-11) by [Unito](https://www.unito.io)

**Comment by graham-russell** [comment]
WIP PR here - https://github.com/ably/terraform-provider-ably/pull/22
