### ISSUE TITLE
Decide on the version number of the first published version of this provider

### ISSUE THREAD

**Issue by kavalerov** [ably/terraform-provider-ably#45]
┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/IAC-52) by [Unito](https://www.unito.io)

**Comment by kavalerov** [comment]
There are several factors to be considered in determining the version number for the Ably Terraform Provider. 

First, the readiness of the provider depends on the [Ably Control API](https://ably.com/docs/api/control-api) which is still "in Preview". 

Second, it depends on [Ably Control Go library ](https://github.com/ably/ably-control-go) which has just been released recently as well. 

Third, provider hasn't been tested yet by our users, and the feedback on the HCL API that we have received so far has been limited. 

Considering the above, and according to SerVer and Ably SDK Product Lifecycle document (https://github.com/ably/engineering/blob/main/sdk/product-lifecycle.md) I suggest we adopt the following versions for the provider releases: 
1) First release (ETA tomorrow, with a very limited set of resources, to test the release flow and Terraform Registry integration) to be `1.0.0-alpha.<build>`, as it fits very well with what is described is Alpha in the lifecycle doc (https://github.com/ably/engineering/blob/main/sdk/product-lifecycle.md)
2) The release that we will make at the end of the sprint and share with the first customers to use and give us feedback to be `1.0.0-beta.<build>`

We will then be able to drop the `beta` signifier after a period of customers using the provider, and us ensuring the stability and sufficient quality of service through the full stack of APIs (Terraform provider, Ably Control Go library and Control API)

**Comment by kavalerov** [comment]
Agree with @Morganamilo after thinking about this: 
- 0.1.0 shows much clearer that it still may not be the stable version of API yet. "Beta" means similar thing, but we know it because of our internal documentation, and external users will not know that. 
- For the test release we can actually adopt even more "cautious" version of 0.0.0 to clearly show that it shouldn't be used yet. 


Based on the above I suggest we name the test release today 0.0.0-alpha, and then a "proper" release next week - 0.1.0-beta.

**Comment by Morganamilo** [comment]
0.0.0 should indicate pre alpha anyway, 0.0.0-alpha would be like calling a version alpha-alpha in my opinion. A bit redundant.

**Comment by QuintinWillison** [comment]
I agree with `0.0.0` for first, test release. Thanks, both.
I'm guessing this issue can now close, the decision having been implemented in #79.
